# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Crane - Cloud Resource Analytics and Economics
theme:
  name: material
  language: en
  features:
    - toc.integrate
  palette:
    primary: blue
  logo: images/crane.svg
  favicon: images/crane.svg
  font:
    text: Work Sans
extra_css:
  - stylesheets/extra.css
plugins:
  - search
markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
repo_url: https://github.com/gocrane/crane
repo_name: gocrane/crane
nav:
  - Overview: index.md
  - Getting Started: getting-started.md
  - Tutorials:
      - Analytics and Recommendation: tutorials/analytics-and-recommendation.md
      - Using Effective HPA To Scaling With Effectiveness: tutorials/using-effective-hpa-to-scaling-with-effectiveness.md
      - Using Qos Ensurance: tutorials/using-qos-ensurance.md
      - Using Time Series Prediction: tutorials/using-time-series-prediction.md
  - Proposals:
      - Advanced CpuSet Manager: proposals/20220228-advanced-cpuset-manger.md
  - Contributing: CONTRIBUTING.md
  - Code Standard: code-standards.md
  - Roadmap:
    - 1H 2022: roadmaps/roadmap-1h-2022.md
