name: Publish branch
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - run: pip install mkdocs-material mkdocs-static-i18n mike

      - name: Set user
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Mike with updating aliases
        if: ${{ github.event.created }}
        run: |
          CURRENT_VERSION=$(echo ${{ steps.extract_branch.outputs.branch }} | cut -d '/' -f3)
          mike deploy --push --force --update-aliases $CURRENT_VERSION latest --rebase
          mike set-default --push --force latest

      - name: Mike
        if: ${{ !github.event.created }}
        run: |
          CURRENT_VERSION=$(echo ${{ steps.extract_branch.outputs.branch }} | cut -d '/' -f3)
          mike deploy --force --push $CURRENT_VERSION
